### ISSUE TITLE
Styling for SearchView

### ISSUE THREAD

**Issue by iamarjun** [sabergeek/android-material-design-in-practice#1]
Hi, awesome example btw, but I was trying to theme the search view but couldn't get it working, can you help me with this

**Comment by sabergeek** [comment]
Hello @iamarjun. Can you share the following details? 

1. Android version you're trying on.
2. Screen reference of desired look of search view
3. Screen reference of how the current styling for search view looks like.

**Comment by iamarjun** [comment]
@sabergeek 
1. Android 10
2. Simple SearchView in the toolbar.
3. As you can see when the search view expands there is a back arrow before the cursor which is currently white, also there are those magnifying glass and cross icons in the search view itself which are white, I tried many solutions but couldn't get it working.
![Screenshot_20200729-213655](https://user-images.githubusercontent.com/19618555/88824372-dfc17380-d1e3-11ea-87a6-4a0debce74c8.png)
![Screenshot_20200729-213702](https://user-images.githubusercontent.com/19618555/88824396-e94adb80-d1e3-11ea-88d8-ede5a145819c.png)

Below is the styling I tried to follow

```
<style name="App.Theme.SearchView" parent="Widget.AppCompat.SearchView">
        <!-- Background for the search query section (e.g. EditText) -->
        <item name="queryBackground">@color/primaryDarkColor</item>
        <!-- Background for the actions section (e.g. voice, submit) -->
        <item name="submitBackground">@color/black_800</item>
        <!-- Close button icon -->
        <item name="closeIconTint">@color/black_800</item>
        <!-- Search button icon -->
        <item name="searchIcon">@color/black_800</item>
        <!-- Go/commit button icon -->
        <item name="goIcon">@color/black_800</item>
        <!-- Voice search button icon -->
        <item name="voiceIcon">@color/black_800</item>
        <!-- Commit icon shown in the query suggestion row -->
        <item name="commitIcon">@color/black_800</item>
        <!-- Layout for query suggestion rows -->
        <item name="suggestionRowLayout">@color/black_800</item>

    </style>
```

**Comment by sabergeek** [comment]
@iamarjun Styling view-groups of widgets can be little tricky. I'll update the repo with a working example soon.

**Comment by sabergeek** [comment]
@iamarjun The repo has been updated with a sample for styling search views. You should basically add _theme_ and _popup theme_ attributes while styling your toolbar. In this repo, the toolbar has been globally styled in themes.xml.

```
    <!-- Toolbar -->

    <style name="ToolbarAppearance" parent="Widget.MaterialComponents.Toolbar.PrimarySurface">
        <item name="popupTheme">@style/ToolbarAppearanceOverlay</item>
        <item name="theme">@style/ToolbarAppearanceOverlay</item>
    </style>

    <!-- For widgets on Toolbar -->

    <style name="ToolbarAppearanceOverlay">
        <item name="android:textColorPrimary">?colorOnPrimary</item>
        <item name="colorControlNormal">?colorOnPrimary</item>
        <item name="colorControlHighlight">?colorOnPrimary</item>
        <item name="android:textColorHint">?colorOnPrimary</item>
    </style>
```

**Update: I noticed the approach only works for themes that extend _Theme.MaterialComponents.DayNight.DarkActionBar_.

For _Theme.MaterialComponents.DayNight.NoActionBar_, _popupTheme_ and _theme_ attributes DO NOT work. Instead, replace them with just one _materialThemeOverlay_ attribute pointing to the overlay style.**

**Comment by iamarjun** [comment]
> @iamarjun The repo has been updated with a sample for styling search views. You should basically add _theme_ and _popup theme_ attributes while styling your toolbar. In this repo, the toolbar has been globally styled in themes.xml.
> 
> ```
>     
> 
>     <style name="ToolbarAppearance" parent="Widget.MaterialComponents.Toolbar.PrimarySurface">
>         <item name="popupTheme">@style/ToolbarAppearanceOverlay</item>
>         <item name="theme">@style/ToolbarAppearanceOverlay</item>
>     </style>
> 
>     
> 
>     <style name="ToolbarAppearanceOverlay">
>         <item name="android:textColorPrimary">?colorOnPrimary</item>
>         <item name="colorControlNormal">?colorOnPrimary</item>
>         <item name="colorControlHighlight">?colorOnPrimary</item>
>         <item name="android:textColorHint">?colorOnPrimary</item>
>     </style>
> ```

Awesome thanks, lemme give it a spin

**Comment by iamarjun** [comment]
@sabergeek Thanks for the efforts, but is there any difference in theming if I were to define my own toolbar using this as parent
```
Theme.MaterialComponents.DayNight.NoActionBar
```
In my case, the search view theming still doesn't get applied
If you look very closely the back button and the cross buttons are stiff white, also before writing the text the magnifying glass icon is also white, you can refer to the previous screenshot that I've attached. You need to look very closely as it is white and not very distinguishable.
![Screenshot_20200731-222752.jpg](https://user-images.githubusercontent.com/19618555/89058611-357d5380-d37d-11ea-89a4-fa1f17facd95.jpg)

**Comment by sabergeek** [comment]
@iamarjun That shouldn't be a problem. Can you share a sample project with your current implementation? I'll look into it.

**Comment by iamarjun** [comment]
> @iamarjun That shouldn't be a problem. Can you share a sample project with your current implementation? I'll look into it.

Sure, https://github.com/iamarjun/Food2Fork/tree/material_design

**Comment by sabergeek** [comment]
@iamarjun Try this:

```
    <!-- Toolbar -->

    <style name="ToolbarAppearance" parent="Widget.MaterialComponents.Toolbar.Primary">
        <item name="materialThemeOverlay">@style/ToolbarAppearanceOverlay</item>
    </style>

    <!-- For widgets on Toolbar -->

    <style name="ToolbarAppearanceOverlay">
        <item name="android:textColorPrimary">?colorOnPrimary</item>
        <item name="colorControlNormal">?colorOnPrimary</item>
        <item name="colorControlHighlight">?colorOnPrimary</item>
        <item name="android:textColorHint">?colorOnPrimary</item>
    </style>

    <!-- You can replace ?colorOnPrimary with any other you like -->

```
The code above produces the following output for _Theme.MaterialComponents.DayNight.NoActionBar_:

![Screenshot_1596223705](https://user-images.githubusercontent.com/876859/89070357-83e91d00-d392-11ea-82b2-21fde5f2a71d.png)

**Comment by iamarjun** [comment]
> 
> 
>     <style name="ToolbarAppearance" parent="Widget.MaterialComponents.Toolbar.Primary">
>         <item name="materialThemeOverlay">@style/ToolbarAppearanceOverlay</item>
>     </style>
> 
>     
> 
>     <style name="ToolbarAppearanceOverlay">
>         <item name="android:textColorPrimary">?colorOnPrimary</item>
>         <item name="colorControlNormal">?colorOnPrimary</item>
>         <item name="colorControlHighlight">?colorOnPrimary</item>
>         <item name="android:textColorHint">?colorOnPrimary</item>
>     </style>
> 
>     

Thanks, @sabergeek it works like a charm, dammit I find it so hard to understand these styling and theming, thanks once again
